/**
 * Códigos de error estables. El backend los devuelve; el frontend los traduce
 * en su locale activo. NO traducir mensajes en el backend.
 */
export const ErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REUSED: 'TOKEN_REUSED',

  // Domain — products
  PRODUCT_SKU_TAKEN: 'PRODUCT_SKU_TAKEN',
  PRODUCT_HAS_DEPENDENCIES: 'PRODUCT_HAS_DEPENDENCIES',
  PRODUCT_VERSION_CONFLICT: 'PRODUCT_VERSION_CONFLICT',
  PRODUCT_ALIAS_TAKEN: 'PRODUCT_ALIAS_TAKEN',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_CODE_TAKEN: 'CATEGORY_CODE_TAKEN',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_PARENT_INVALID: 'CATEGORY_PARENT_INVALID',

  // Domain — recipes
  RECIPE_CODE_TAKEN: 'RECIPE_CODE_TAKEN',
  RECIPE_VERSION_CONFLICT: 'RECIPE_VERSION_CONFLICT',
  RECIPE_HAS_DEPENDENCIES: 'RECIPE_HAS_DEPENDENCIES',
  RECIPE_LINE_INVALID: 'RECIPE_LINE_INVALID',
  RECIPE_CYCLE_DETECTED: 'RECIPE_CYCLE_DETECTED',
  RECIPE_PRODUCT_NOT_FOUND: 'RECIPE_PRODUCT_NOT_FOUND',
  RECIPE_SUBRECIPE_NOT_FOUND: 'RECIPE_SUBRECIPE_NOT_FOUND',

  // Domain — inventory
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  WAREHOUSE_INACTIVE: 'WAREHOUSE_INACTIVE',

  // Domain — audit
  AUDIT_NOT_IN_PROGRESS: 'AUDIT_NOT_IN_PROGRESS',
  AUDIT_ALREADY_RECONCILED: 'AUDIT_ALREADY_RECONCILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ApiErrorBody {
  code: ErrorCode;
  message?: string; // mensaje técnico EN para devs/logs, NO se muestra al usuario
  params?: Record<string, unknown>;
  fieldErrors?: Record<string, string[]>;
  requestId?: string;
}
